# Generated by Django 3.2.13 on 2023-05-03 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artilheiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('jogos', models.CharField(max_length=4)),
                ('gols', models.CharField(max_length=3)),
                ('titulos', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Nacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('ano', models.CharField(max_length=4)),
                ('tipo', models.CharField(max_length=10)),
                ('invicto', models.BooleanField()),
            ],
        ),
    ]
